version: '3.8'

services:
  nodejs:
    image: node:18
    container_name: attendance_services
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: [ "node", "index.js" ]

  redis:
    image: redis:latest
    container_name: attendance_redis_server
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: attendance_elasticsearch_server
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  mysql:
    image: mysql:8
    container_name: attendance_mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_apps
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
